package com.odaria.api.commons.message;

public enum MessageAction {
    CHANGE_SERVER_STATE,
    SAVE_ACCOUNT_TO_DATABASE,
    LOAD_ACCOUNT_FROM_DATABASE,
    SEND_FRIEND_REQUEST,
    ACCEPT_FRIEND_REQUEST,
    DENY_FRIEND_REQUEST,
    REMOVE_FRIEND,
    SEND_MAX_PLAYERS,
    INVITE_PLAYER_PARTY,
    TELEPORT_PLAYERS_PARTY,
    TELEPORT_ALL_PLAYERS_TO_HUB,
    ADD_REWARDS,
    JOIN_GAME;
}
